package cli

import (
	"fmt"
	"regexp"

	"github.com/spf13/cobra"

	"github.com/ethangardner/gomaat/internal/analysis"
	"github.com/ethangardner/gomaat/internal/grouper"
	"github.com/ethangardner/gomaat/internal/model"
	"github.com/ethangardner/gomaat/internal/parser"
	"github.com/ethangardner/gomaat/internal/teammapper"
)

// defaultBugfixPattern is used when neither --bugfix-pattern nor
// --conventional-commit-type is given. Documented explicitly in the flag
// help and README so users know what's being matched by default.
const defaultBugfixPattern = `(?i)fix|bug|defect|hotfix`

func newDefectsCmd() *cobra.Command {
	var pattern string
	var conventionalType string

	cmd := &cobra.Command{
		Use:   "defects",
		Short: "Defect density per entity via commit message classification",
		Long: `Classifies commits as bug fixes by matching their message against a
pattern, then reports defect density (bugfix revisions vs. total revisions)
per entity. Requires commit messages, so the log must be generated by a
gomaat version that captures them (see 'generate-log').

Examples:
  gomaat defects -l logfile.log
  gomaat defects -l logfile.log --bugfix-pattern '(?i)^fix'
  gomaat defects -l logfile.log --conventional-commit-type fix`,
		RunE: func(cmd *cobra.Command, args []string) error {
			if logFile == "" {
				return fmt.Errorf("--log (-l) is required")
			}
			if err := validateOutputFormat(); err != nil {
				return err
			}
			if pattern != "" && conventionalType != "" {
				return fmt.Errorf("specify only one of --bugfix-pattern or --conventional-commit-type")
			}

			isBugfix, err := bugfixClassifier(pattern, conventionalType)
			if err != nil {
				return err
			}

			commits, err := parser.ParseFile(logFile)
			if err != nil {
				return err
			}
			if groupFile != "" {
				groups, err := grouper.LoadFile(groupFile)
				if err != nil {
					return err
				}
				commits = grouper.Apply(commits, groups)
			}
			if teamMapFile != "" {
				lookup, err := teammapper.LoadFile(teamMapFile)
				if err != nil {
					return err
				}
				commits = teammapper.Apply(commits, lookup)
			}

			results := analysis.Defects(commits, isBugfix, model.Options{})
			return writeRows(analysis.FormatDefects(results, model.Options{}))
		},
	}

	cmd.Flags().StringVar(&pattern, "bugfix-pattern", "", fmt.Sprintf("regex to classify a commit message as a bug fix (default: %q)", defaultBugfixPattern))
	cmd.Flags().StringVar(&conventionalType, "conventional-commit-type", "", `match a Conventional Commits prefix instead (e.g. "fix" matches "fix:"/"fix(scope):")`)

	return cmd
}

// bugfixClassifier builds the commit predicate for --bugfix-pattern or
// --conventional-commit-type (mutual exclusivity is checked by the caller),
// falling back to defaultBugfixPattern when neither flag is set.
func bugfixClassifier(pattern, conventionalType string) (func(model.Commit) bool, error) {
	if conventionalType != "" {
		re, err := regexp.Compile(`(?m)^` + regexp.QuoteMeta(conventionalType) + `(\([^)]*\))?:`)
		if err != nil {
			return nil, fmt.Errorf("--conventional-commit-type: invalid: %w", err)
		}
		return func(c model.Commit) bool { return re.MatchString(c.Message) }, nil
	}

	p := pattern
	if p == "" {
		p = defaultBugfixPattern
	}
	re, err := regexp.Compile(p)
	if err != nil {
		return nil, fmt.Errorf("--bugfix-pattern: invalid regex: %w", err)
	}
	return func(c model.Commit) bool { return re.MatchString(c.Message) }, nil
}
