package parser

import (
	"bufio"
	"fmt"
	"io"
	"os"
	"strconv"
	"strings"

	"gomaat/internal/model"
)

// ParseFile reads a git-format log file and returns all commits.
// Log format generated by:
//
//	git log --all --numstat --date=short --pretty=format:'--%h--%ad--%aN' --no-renames
//
// Each entry:
//
//	--<rev>--<date>--<author>
//	<added>\t<deleted>\t<filepath>
//	...
//	(blank line separates entries)
func ParseFile(path string) ([]model.Commit, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, fmt.Errorf("opening log file: %w", err)
	}
	defer func(f *os.File) {
		err := f.Close()
		if err != nil {
			_, _ = fmt.Fprintf(os.Stderr, "error closing log file %s: %v\n", path, err)
		}
	}(f)
	return parse(f)
}

func ParseReader(r io.Reader) ([]model.Commit, error) {
	return parse(r)
}

func parse(r io.Reader) ([]model.Commit, error) {
	var commits []model.Commit
	scanner := bufio.NewScanner(r)

	var currentRev, currentDate, currentAuthor string

	for scanner.Scan() {
		line := scanner.Text()

		if strings.HasPrefix(line, "--") {
			// commit header: --rev--date--author
			parts := strings.SplitN(line, "--", 4)
			// parts[0] is empty (before first --)
			if len(parts) < 4 {
				continue
			}
			currentRev = parts[1]
			currentDate = parts[2]
			currentAuthor = parts[3]
			continue
		}

		if currentRev == "" {
			continue
		}

		if strings.TrimSpace(line) == "" {
			continue
		}

		// file change line: added\tdeleted\tfilepath
		parts := strings.SplitN(line, "\t", 3)
		if len(parts) < 3 {
			continue
		}

		added := parseNumstat(parts[0])
		deleted := parseNumstat(parts[1])
		entity := strings.TrimSpace(parts[2])

		commits = append(commits, model.Commit{
			Rev:        currentRev,
			Date:       currentDate,
			Author:     currentAuthor,
			Entity:     entity,
			LocAdded:   added,
			LocDeleted: deleted,
		})
	}

	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("reading log: %w", err)
	}
	return commits, nil
}

// parseNumstat converts a numstat field ("-" for binary, or a number) to int.
func parseNumstat(s string) int {
	s = strings.TrimSpace(s)
	if s == "-" {
		return 0
	}
	n, _ := strconv.Atoi(s)
	return n
}
