package parser

import (
	"bytes"
	"fmt"
	"io"
	"os"
	"strconv"
	"strings"

	"github.com/ethangardner/gomaat/internal/model"
)

// ParseFile reads a git-format log file and returns all commits.
// Log format generated by:
//
//	git log --all --numstat --date=short --pretty=format:'%x00%H%x00%ad%x00%aN%x00%B%x00' --no-renames --no-merges
//
// --no-merges excludes merge commits so a combined merge diff never gets
// double-counted against the commits it merges.
//
// Each commit is emitted as a NUL-delimited record:
//
//	\x00<rev>\x00<date>\x00<author>\x00<message>\x00
//	<added>\t<deleted>\t<filepath>
//	...
//
// NUL bytes are used to delimit fields (rather than a text sentinel) because
// git commit messages cannot contain embedded NUL bytes, so they're the only
// byte sequence guaranteed absent from arbitrary message content — including
// a message that happens to contain a line starting with "--" or a blank
// line, either of which would break a text-based delimiter.
func ParseFile(path string) ([]model.Commit, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, fmt.Errorf("opening log file: %w", err)
	}
	defer func(f *os.File) {
		err := f.Close()
		if err != nil {
			_, _ = fmt.Fprintf(os.Stderr, "error closing log file %s: %v\n", path, err)
		}
	}(f)
	return parse(f)
}

func ParseReader(r io.Reader) ([]model.Commit, error) {
	return parse(r)
}

func parse(r io.Reader) ([]model.Commit, error) {
	data, err := io.ReadAll(r)
	if err != nil {
		return nil, fmt.Errorf("reading log: %w", err)
	}
	if len(data) == 0 {
		return nil, nil
	}
	if !bytes.Contains(data, []byte{0}) {
		return nil, fmt.Errorf("log file is not in the expected format (no NUL-delimited commit records found) — regenerate it with 'gomaat generate-log'")
	}

	// Splitting on NUL yields, after dropping the empty prefix before the
	// very first commit's leading NUL, groups of 5 fields per commit:
	// rev, date, author, message, and the raw numstat block (everything
	// between this commit's closing NUL and the next commit's leading NUL,
	// or EOF for the last commit).
	fields := bytes.Split(data, []byte{0})
	fields = fields[1:]

	var commits []model.Commit
	for i := 0; i+4 < len(fields); i += 5 {
		rev := string(fields[i])
		date := string(fields[i+1])
		author := string(fields[i+2])
		message := strings.TrimRight(string(fields[i+3]), "\n")
		numstatBlock := string(fields[i+4])

		for _, line := range strings.Split(numstatBlock, "\n") {
			if strings.TrimSpace(line) == "" {
				continue
			}

			// file change line: added\tdeleted\tfilepath
			parts := strings.SplitN(line, "\t", 3)
			if len(parts) < 3 {
				continue
			}

			commits = append(commits, model.Commit{
				Rev:        rev,
				Date:       date,
				Author:     author,
				Entity:     strings.TrimSpace(parts[2]),
				Message:    message,
				LocAdded:   parseNumstat(parts[0]),
				LocDeleted: parseNumstat(parts[1]),
			})
		}
	}

	return commits, nil
}

// parseNumstat converts a numstat field ("-" for binary, or a number) to int.
func parseNumstat(s string) int {
	s = strings.TrimSpace(s)
	if s == "-" {
		return 0
	}
	// git numstat produces integers or "-" (handled above); treat anything
	// else as 0 rather than failing the entire parse.
	n, _ := strconv.Atoi(s)
	return n
}
